"""Initial migration

Revision ID: 17336cb22525
Revises: 
Create Date: 2025-12-09 18:05:38.655098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17336cb22525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_advertisement'))
    )
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('target_role', sa.Enum('CITIZEN', 'MEMBER_HEAD', 'FIELD_STAFF', 'ADMIN', name='role'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_announcement'))
    )
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.create_index('ix_announcement_expires_active', ['expires_at', 'is_active'], unique=False)
        batch_op.create_index('ix_announcement_target_role', ['target_role'], unique=False)

    op.create_table('master_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_areas'))
    )
    with op.batch_alter_table('master_areas', schema=None) as batch_op:
        batch_op.create_index('ix_master_areas_active', ['is_active'], unique=False)

    op.create_table('master_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_categories'))
    )
    with op.batch_alter_table('master_categories', schema=None) as batch_op:
        batch_op.create_index('ix_master_categories_active', ['is_active'], unique=False)

    op.create_table('master_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_config')),
    sa.UniqueConstraint('key', name=op.f('uq_master_config_key'))
    )
    op.create_table('nearby_places',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nearby_places'))
    )
    with op.batch_alter_table('nearby_places', schema=None) as batch_op:
        batch_op.create_index('ix_nearby_category_name', ['category', 'name'], unique=False)
        batch_op.create_index('ix_nearby_updated', ['updated_at'], unique=False)

    op.create_table('master_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['master_categories.id'], name=op.f('fk_master_subjects_category_id_master_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_subjects'))
    )
    with op.batch_alter_table('master_subjects', schema=None) as batch_op:
        batch_op.create_index('ix_master_subjects_active', ['is_active'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('voter_id', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Enum('CITIZEN', 'MEMBER_HEAD', 'FIELD_STAFF', 'ADMIN', name='role'), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('profile_picture', sa.String(length=256), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['master_areas.id'], name=op.f('fk_user_department_id_master_areas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_user_phone_number')),
    sa.UniqueConstraint('voter_id', name=op.f('uq_user_voter_id'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.create_index('ix_user_phone', ['phone_number'], unique=False)
        batch_op.create_index('ix_user_role_created', ['role', 'created_at'], unique=False)

    op.create_table('grievance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.String(length=50), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ward_number', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'IN_PROGRESS', 'ON_HOLD', 'RESOLVED', 'CLOSED', 'REJECTED', name='grievancestatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='priority'), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('escalation_level', sa.Integer(), nullable=True),
    sa.Column('feedback_rating', sa.Integer(), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['master_areas.id'], name=op.f('fk_grievance_area_id_master_areas')),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], name=op.f('fk_grievance_assigned_by_user')),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], name=op.f('fk_grievance_assigned_to_user')),
    sa.ForeignKeyConstraint(['category_id'], ['master_categories.id'], name=op.f('fk_grievance_category_id_master_categories')),
    sa.ForeignKeyConstraint(['citizen_id'], ['user.id'], name=op.f('fk_grievance_citizen_id_user')),
    sa.ForeignKeyConstraint(['subject_id'], ['master_subjects.id'], name=op.f('fk_grievance_subject_id_master_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievance')),
    sa.UniqueConstraint('complaint_id', name=op.f('uq_grievance_complaint_id'))
    )
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.create_index('ix_grievance_assigned', ['assigned_to', 'assigned_by'], unique=False)
        batch_op.create_index('ix_grievance_citizen_created', ['citizen_id', 'created_at'], unique=False)
        batch_op.create_index('ix_grievance_location', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('ix_grievance_priority_escalation', ['priority', 'escalation_level'], unique=False)
        batch_op.create_index('ix_grievance_status_updated', ['status', 'updated_at'], unique=False)

    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_preference_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preference'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=True),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievance.id'], name=op.f('fk_audit_log_grievance_id_grievance')),
    sa.ForeignKeyConstraint(['performed_by'], ['user.id'], name=op.f('fk_audit_log_performed_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_performed_by', ['performed_by'], unique=False)
        batch_op.create_index('ix_audit_timestamp_grievance', ['timestamp', 'grievance_id'], unique=False)

    op.create_table('grievance_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievance.id'], name=op.f('fk_grievance_attachment_grievance_id_grievance')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievance_attachment'))
    )
    op.create_table('grievance_comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievance.id'], name=op.f('fk_grievance_comment_grievance_id_grievance')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_grievance_comment_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grievance_comment'))
    )
    op.create_table('workproof',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grievance_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grievance_id'], ['grievance.id'], name=op.f('fk_workproof_grievance_id_grievance')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], name=op.f('fk_workproof_uploaded_by_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workproof'))
    )
    op.create_table('comment_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['grievance_comment.id'], name=op.f('fk_comment_attachment_comment_id_grievance_comment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comment_attachment'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_attachment')
    op.drop_table('workproof')
    op.drop_table('grievance_comment')
    op.drop_table('grievance_attachment')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_timestamp_grievance')
        batch_op.drop_index('ix_audit_performed_by')

    op.drop_table('audit_log')
    op.drop_table('user_preference')
    with op.batch_alter_table('grievance', schema=None) as batch_op:
        batch_op.drop_index('ix_grievance_status_updated')
        batch_op.drop_index('ix_grievance_priority_escalation')
        batch_op.drop_index('ix_grievance_location')
        batch_op.drop_index('ix_grievance_citizen_created')
        batch_op.drop_index('ix_grievance_assigned')

    op.drop_table('grievance')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_role_created')
        batch_op.drop_index('ix_user_phone')
        batch_op.drop_index('ix_user_email')

    op.drop_table('user')
    with op.batch_alter_table('master_subjects', schema=None) as batch_op:
        batch_op.drop_index('ix_master_subjects_active')

    op.drop_table('master_subjects')
    with op.batch_alter_table('nearby_places', schema=None) as batch_op:
        batch_op.drop_index('ix_nearby_updated')
        batch_op.drop_index('ix_nearby_category_name')

    op.drop_table('nearby_places')
    op.drop_table('master_config')
    with op.batch_alter_table('master_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_master_categories_active')

    op.drop_table('master_categories')
    with op.batch_alter_table('master_areas', schema=None) as batch_op:
        batch_op.drop_index('ix_master_areas_active')

    op.drop_table('master_areas')
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_index('ix_announcement_target_role')
        batch_op.drop_index('ix_announcement_expires_active')

    op.drop_table('announcement')
    op.drop_table('advertisement')
    # ### end Alembic commands ###
